// menuData.js
const menuItems = [
  {
    name: 'Grilled Chicken Salad',
    dietaryRestrictions: [],
    allergies: [],
    preferences: ['low-calorie', 'high-protein'],
    image: 'grilled-chicken-salad.jpg',
    calories: 350,
    protein: 25,
    carbs: 10,
    fat: 15,
  },
  {
    name: 'Vegan Burger',
    dietaryRestrictions: ['vegan'],
    allergies: ['gluten'],
    preferences: ['high-protein'],
    image: 'vegan-burger.jpg',
    calories: 400,
    protein: 20,
    carbs: 30,
    fat: 12,
  },
  {
    name: 'Gluten-free Pasta',
    dietaryRestrictions: ['gluten-free'],
    allergies: [],
    preferences: [],
    image: 'gluten-free-pasta.jpg',
    calories: 450,
    protein: 15,
    carbs: 60,
    fat: 10,
  },
  {
    name: 'Spicy Tofu Stir-fry',
    dietaryRestrictions: ['vegan'],
    allergies: [],
    preferences: ['spicy'],
    image: 'spicy-tofu-stir-fry.jpg',
    calories: 300,
    protein: 18,
    carbs: 25,
    fat: 12,
  },
  {
    name: 'Peanut Butter Sandwich',
    dietaryRestrictions: [],
    allergies: ['peanuts'],
    preferences: ['high-protein'],
    image: 'peanut-butter-sandwich.jpg',
    calories: 400,
    protein: 15,
    carbs: 40,
    fat: 20,
  },
  {
    name: 'Halal Lamb Curry',
    dietaryRestrictions: ['halal'],
    allergies: [],
    preferences: ['spicy', 'high-protein'],
    image: 'halal-lamb-curry.jpg',
    calories: 500,
    protein: 30,
    carbs: 35,
    fat: 20,
  },
  {
    name: 'Kosher Salmon',
    dietaryRestrictions: ['kosher'],
    allergies: [],
    preferences: ['low-calorie', 'high-protein'],
    image: 'kosher-salmon.jpg',
    calories: 350,
    protein: 28,
    carbs: 5,
    fat: 15,
  },
  {
    name: 'Lactose-free Yogurt Parfait',
    dietaryRestrictions: ['lactose-free'],
    allergies: [],
    preferences: ['low-calorie'],
    image: 'lactose-free-yogurt-parfait.jpg',
    calories: 250,
    protein: 12,
    carbs: 30,
    fat: 8,
  },
  {
    name: 'Vegetarian Pizza',
    dietaryRestrictions: ['vegetarian'],
    allergies: ['gluten'],
    preferences: ['high-protein'],
    image: 'vegetarian-pizza.jpg',
    calories: 450,
    protein: 18,
    carbs: 50,
    fat: 15,
  },
  {
    name: 'Pescatarian Sushi',
    dietaryRestrictions: ['pescatarian'],
    allergies: ['soy'],
    preferences: ['low-calorie'],
    image: 'pescatarian-sushi.jpg',
    calories: 300,
    protein: 20,
    carbs: 40,
    fat: 10,
  },
  {
    name: 'Sugar-free Dessert',
    dietaryRestrictions: [],
    allergies: [],
    preferences: ['sugar-free'],
    image: 'sugar-free-dessert.jpg',
    calories: 200,
    protein: 5,
    carbs: 20,
    fat: 10,
  },
  {
    name: 'Quinoa Salad',
    dietaryRestrictions: ['vegan', 'gluten-free'],
    allergies: [],
    preferences: ['high-protein', 'low-calorie'],
    image: 'quinoa-salad.jpg',
    calories: 320,
    protein: 12,
    carbs: 40,
    fat: 10,
  },
  {
    name: 'Grilled Tofu Skewers',
    dietaryRestrictions: ['vegan', 'gluten-free'],
    allergies: ['soy'],
    preferences: ['high-protein', 'low-calorie'],
    image: 'grilled-tofu-skewers.jpg',
    calories: 280,
    protein: 20,
    carbs: 15,
    fat: 12,
  },
  {
    name: 'Chickpea Curry',
    dietaryRestrictions: ['vegan', 'gluten-free'],
    allergies: [],
    preferences: ['spicy', 'high-protein'],
    image: 'chickpea-curry.jpg',
    calories: 400,
    protein: 18,
    carbs: 40,
    fat: 15,
  },
  {
    name: 'Keto Chicken Alfredo',
    dietaryRestrictions: [],
    allergies: ['dairy'],
    preferences: ['low-carb', 'high-protein'],
    image: 'keto-chicken-alfredo.jpg',
    calories: 450,
    protein: 35,
    carbs: 10,
    fat: 30,
  },
];

export default menuItems;